kind: pipeline
name: default

steps:
  - name: build
    image: golang:latest
    group: build
    volumes:
      - name: build
        path: /build
    commands:
     - mkdir -p /build/i386 /build/amd64 /build/armv7 /build/arm64
     - GOOS=linux GOARCH=386 go build -o /build/i386/owapi
     - go build -o /build/amd64/owapi
     - GOOS=linux GOARCH=arm GOARM=7 go build -o /build/armv7/owapi
     - GOOS=linux GOARCH=arm64 go build -o /build/arm64/owapi
  - name: package
    image: tystuyfzand/fpm
    commands:
     - export VERSION=`grep "Version" main.go | head -n 1 | awk '{print $3}' | sed -e 's/^"//' -e 's/"$//' | tr -d '\n'`
     - chmod +x packaging/build-package.sh packaging/package-upload.sh
     - ARCH=i386 packaging/build-package.sh
     - ARCH=amd64 packaging/build-package.sh
     - ARCH=armv7 packaging/build-package.sh
     - ARCH=arm64 packaging/build-package.sh
     - packaging/package-upload.sh
    volumes:
      - name: build
        path: /build
    environment:
      UPLOAD_URL:
        from_secret: upload_url

volumes:
  - name: build
    temp: {}